### ISSUE TITLE
Add support to add own documents

### ISSUE THREAD

**Issue by schnettker** [serge-chat/serge#450] opened 2023-06-19 12:20 UTC
### Bug description

Hi,

is it possible to add own documents (Like h2ogpt)?

### Steps to reproduce

-

### Environment Information

-

### Confirmations

- [X] I'm running the latest version of the main branch.
- [X] I checked existing issues to see if this has already been described.

**Comment by gaby** [comment] 2023-06-19 12:21
@schnettker It's not supported yet. We have talked about it on Discord. It would require major restructuring of the project

**Comment by schnettker** [comment] 2023-06-19 12:22
thank you for the fast reply. I starred the project and keep an eye on it

**Comment by gaby** [comment] 2023-06-19 12:22
> thank you for the fast reply. I starred the project and keep an eye on it

Thanks 🙌 will keep this open, for the future

**Comment by gaby** [comment] 2023-07-01 23:54
Duplicate of #17

**Closed by gaby** 2023-07-01 23:54 UTC
Labels: bug
