### ISSUE TITLE
Switching conversations while the chat is answering shows the answer in whichever chat is focused.

### ISSUE THREAD

**Issue by nsarrazin** [serge-chat/serge#20] opened 2023-03-22 21:03 UTC
If you ask an answer and switch conversations while it's answering you, the answer will follow you around and continue streaming. 

If you refresh the page afterwards, it's gone and the answer will be in the right chat, so this is just a rendering bug, not a big deal but would be nice to fix.

**Comment by gaby** [comment] 2023-09-17 22:57
Duplicate of #744

**Closed by gaby** 2023-09-17 22:57 UTC
Labels: 🌐 Web, ☢️ Bug
