### ISSUE TITLE
🚀 [Feature]: User Management for Privacy

### ISSUE THREAD

**Issue by SolutionsKrezus** [serge-chat/serge#950] opened 2023-12-05 15:41 UTC
### Feature Description

Currently, all prompt history is public. A system to manage users would allow several people to use Serge without other users being able to see each other's history.
This function could be supplemented by the possibility of giving permissions to users.
For example: User1 only has access to Airoboros-13B with 8 cores.

### Additional Context (optional)

Hello and thank you for this great application.
I have been using Serge for several months at home with my family and at work with colleagues. However, the fact that there are no users makes reading the prompt history complicated, and the lack of confidentiality pushes us to turn to paid and individual solutions.

This function would allow us to share a server while keeping reading clear and private.

Thanks !

### Checklist:

- [X] I have checked for existing issues that describe my suggestion prior to opening this one.
- [X] I understand that improperly formatted feature requests may be closed without explanation.

**Comment by gaby** [comment] 2023-12-06 01:31
Thanks for the feature request. This is a duplicate of #632

**Closed** 2024-07-27 18:48 UTC
Labels: ✏️ Feature, 💡 Help Wanted, 👍 Accepting PR
